ALTER TABLE "AppSettings" ADD COLUMN IF NOT EXISTS "waWebState" TEXT NOT NULL DEFAULT 'disconnected';
ALTER TABLE "AppSettings" ADD COLUMN IF NOT EXISTS "waWebQr" TEXT NOT NULL DEFAULT '';
ALTER TABLE "AppSettings" ADD COLUMN IF NOT EXISTS "waWebError" TEXT NOT NULL DEFAULT '';
ALTER TABLE "AppSettings" ADD COLUMN IF NOT EXISTS "waWebCreds" TEXT NOT NULL DEFAULT '';
ALTER TABLE "AppSettings" ADD COLUMN IF NOT EXISTS "waWebPairId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "AppSettings" ADD COLUMN IF NOT EXISTS "waWebPairingUntil" TIMESTAMP(3);
